### ISSUE TITLE
Fragpipe Crashes with Phospho modifications enabled

### ISSUE THREAD

**Issue by nicolasgrinberg** [Nesvilab/FragPipe#1339]
- Hi, I'm trying to use fragpipe in hybrid DIA mode with DIAUmpire and DIANN enabled on immunopeptidomics data. It seems like the number of possible peptides explodes past the 2 billion possible peptides allowed. Since I am working in DIA, fragpipe doesn't allow me to split the database unfortunately. I tried lowering the max number of modifications down to 2 and max combinations down to 4000 but it still crashes. This dataset is from class II peptides with an amino acid range from 8 to 25. I am running with 30 cores and 150 gb of RAM. I don't really know where I could be going wrong. I know the files are not corrupted since I used them recently on a search without phospho enable. Thank you in advance
- 
[fragpipe.workflow.txt](https://github.com/Nesvilab/FragPipe/files/13403001/fragpipe.workflow.txt)

[log_2023-11-18_17-33-40.txt](https://github.com/Nesvilab/FragPipe/files/13402990/log_2023-11-18_17-33-40.txt)
[diaumpire_se.log](https://github.com/Nesvilab/FragPipe/files/13402991/diaumpire_se.log)

**Comment by fcyu** [comment]
With the DIA-Umpire enabled, we can actually make the split database option work. Could you download the pre-release version from https://www.dropbox.com/t/kgYzMZJem1u8GBT9 and try again?

Thanks,

Fengchao

**Comment by nicolasgrinberg** [comment]
Thanks! Does the pre-release allow me to use MSBoost while splitting database?

**Comment by nicolasgrinberg** [comment]
Hi Fengchao, thank you for your reply. I attempted to run it on the build you provided but it still crashed. I got the following error:

Done generating DIA-NN predictions
Model running took 70544 milliseconds
Generating edited pin with following features: [unweightedSpectralEntropy, deltaRTLOESS]
Loading predicted spectra
Processing 20230825_DIA_INT001-02674-HLAIp_R02_Q1.mzML
java.lang.NullPointerException: Cannot invoke "java.lang.Double.doubleValue()" because the return value of "umich.ms.datatypes.scan.props.PrecursorInfo.getMzRangeStart()" is null
	at Features.MzmlScanNumber.<init>(MzmlScanNumber.java:56)
	at Features.MzmlReader.createScanNumObjects(MzmlReader.java:235)
	at Features.MzmlReader.<init>(MzmlReader.java:97)
	at Features.PercolatorFormatter.editPin(PercolatorFormatter.java:326)
	at Features.MainClass.main(MainClass.java:607)
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 1105 remaining tasks

**Comment by fcyu** [comment]
This error seems to be due to a different reason: something was not right in your `20230825_DIA_INT001-02674-HLAIp_R02_Q1.mzML`. Could you share your log file and the mzML file with us?

Thanks,

Fengchao

**Comment by fcyu** [comment]
The link is wrong. Could you re-upload it again?

Best,

Fengchao

**Comment by nicolasgrinberg** [comment]
[log_2023-11-22_23-55-31.txt](https://github.com/Nesvilab/FragPipe/files/13457679/log_2023-11-22_23-55-31.txt)

How about now

**Comment by fcyu** [comment]
Thanks for your files. 

The error was due to a bug in MSBooster:

https://github.com/Nesvilab/MSBooster/blob/4a9466242093fe68d541b4115be191fcbcd21d26/src/main/java/Features/MzmlScanNumber.java#L56-L57

Kevin @yangkl96 , can you take a look? When there are no isolation window MZs in the mzML file, `getMzRangeStart()` and `getMzRangeEnd()` return `null`. Assigning them to `double` will cause exceptions. 

Also, it seems that you used those two values as scan numbers but they are actually isolation low and high MZ values. See my comments in https://github.com/Nesvilab/MSBooster/issues/3

Best,

Fengchao

**Comment by yangkl96** [comment]
Hi Fengchao, I have fixed the error and skip assigning values for the isolation window ranges when that information is missing in the mzml file

**Comment by fcyu** [comment]
Thanks Kevin @yangkl96 .

Hi @nicolasgrinberg , Kevin has fixed MSBooster. Could you try the pre-release version from https://www.dropbox.com/t/RT9b3vq13mlhheyx

Thanks,

Fengchao

**Comment by nicolasgrinberg** [comment]
Hi, I tried. I got a bit further but it still crashed:

Percolator: Convert to pepxml [Work dir: D:\Nicolas\Drug_treatments\Class1\DIA_results\phospho]
java -cp C:\DATA\fragpipe_phosphofix\lib/* com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML 20230828_DIA_INT001-02721-HLAIp_R02_Q2.pin 20230828_DIA_INT001-02721-HLAIp_R02_Q2 20230828_DIA_INT001-02721-HLAIp_R02_Q2_percolator_target_psms.tsv 20230828_DIA_INT001-02721-HLAIp_R02_Q2_percolator_decoy_psms.tsv interact-20230828_DIA_INT001-02721-HLAIp_R02_Q2 DDA 0.5 D:\Nicolas\Drug_treatments\Class1\DIA_results\phospho\20230828_DIA_INT001-02721-HLAIp_R02_Q2_calibrated.mzML
Exception in thread "main" java.lang.NumberFormatException: For input string: "0,1835"
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
	at java.base/jdk.internal.math.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.base/java.lang.Float.parseFloat(Float.java:555)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.percolatorToPepXML(PercolatorOutputToPepXML.java:340)
	at com.dmtavt.fragpipe.tools.percolator.PercolatorOutputToPepXML.main(PercolatorOutputToPepXML.java:59)
Process 'Percolator: Convert to pepxml' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 885 remaining tasks

I included the log file

**Comment by fcyu** [comment]
`Exception in thread "main" java.lang.NumberFormatException: For input string: "0,1835"` 

It seems that Percolator wrote `0,1835` but not `0.1835`. Are you in a country that uses `,` rather than `.` as the decimal point? I am afraid you have to change the configuration/local of your computer to make it use `.`

Best,

Fengchao

**Comment by nicolasgrinberg** [comment]
Ugh my institute gave us a server in french that explains it. We set the language back to english
