### ISSUE TITLE
Issue with MSFragger interface with Koina Server

### ISSUE THREAD

**Issue by BenSamy2020** [Nesvilab/FragPipe#1775]
Greetings @fcyu,

I am experiancing the error of: **{"error":"in ensemble 'Prosit_2020_intensity_HCD', Failed to process the request(s) for model instance 'Prosit_Preprocess_charge', message: IndexError: index 6 is out of bounds for axis 0 with size 6\n\nAt:\n  /models/repo/Prosit_Preprocess_charge/1/model.py(14): indices_to_one_hot\n  /models/repo/Prosit_Preprocess_charge/1/model.py(18): <listcomp>\n  /models/repo/Prosit_Preprocess_charge/1/model.py(18): to_on_hot\n  /models/repo/Prosit_Preprocess_charge/1/model.py(37): execute\n"}** 

Have attatched the log files here for your reference.
[log_2024-09-09_08-42-57.txt](https://github.com/user-attachments/files/16924263/log_2024-09-09_08-42-57.txt)

Please do advise me on how to troubleshoot, thank you.

*I am not sure if I should post this issues here, if its need to be reported to Koina Server team, please do let me know.*

**Comment by fcyu** [comment]
I will let Kevin @yangkl96 to answer the Koina question.

Best,

Fengchao

**Comment by yangkl96** [comment]
Hi Ben,

This error is caused by peptides with charges higher than 6 not being properly filtered out during Prosit's NCE calibration. This error is fixed in the newest MSBooster here: https://www.dropbox.com/scl/fo/sioaysait4lkbdkvk5bn6/AKGomsKTlP6fSup8nnL43YE?rlkey=3k61o6l0o2wsg3m5ml2buv4f1&st=uo0bx12v&dl=0

Please let me know if this fixes the error.

Thanks for your bug reporting,
Kevin

**Comment by BenSamy2020** [comment]
Greetings @yangkl96,

I am still facing issues with MSBooster.

Error: Could not find or load main class Features.MainClass
Caused by: java.lang.ClassNotFoundException: Features.MainClass
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping


[log_2024-09-11_12-59-55.txt](https://github.com/user-attachments/files/16961489/log_2024-09-11_12-59-55.txt)

**Comment by BenSamy2020** [comment]
Can I delete the older MSBooster version?

**Comment by yangkl96** [comment]
Yes

**Comment by BenSamy2020** [comment]
I am having issues with the3 step of: 

2024-09-12 12:26:56 [ERROR] - {"error":"in ensemble 'Prosit_2019_intensity', Failed to process the request(s) for model instance 'Prosit_Preprocess_peptide', message: TypeError: object of type 'NoneType' has no len()\n\nAt:\n  /models/repo/Prosit_Preprocess_peptide/1/sequence_conversion.py(72): character_to_array\n  /models/repo/Prosit_Preprocess_peptide/1/model.py(25): <listcomp>\n  /models/repo/Prosit_Preprocess_peptide/1/model.py(25): execute\n"}
2024-09-12 12:26:56 [ERROR] - D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_MOD_1\SLAS1_UNKNOWN_CANCER_FEMALE_272\best_model\Pr

[Uploading log_2024-09-12_12-32-27.txt…]()

**Comment by BenSamy2020** [comment]
Can the Koina serve models handle these modification: 
![image](https://github.com/user-attachments/assets/5e7840db-239a-42a9-81c4-5b8b76c76333)

**Comment by yangkl96** [comment]
Only AlphaPeptDeep will be able to support the modifications such as C-terminal PTMs and carbamidomethylation of noncysteine amino acids, since it attempts to predict all PTMs in UniMod. I have previously not tested MSBooster for C-terminal modifications, hence the errors. Do you mind sharing with me one mzml and its associated pin file? I can make the necessary changes and send you a working version.

**Comment by BenSamy2020** [comment]
Hi, please share dropbox link. thanks

**Comment by BenSamy2020** [comment]
Also, I suggest adding a warning or stop message upon clicking the start run button of the GUI to remind users that mods that are not trained on prosit cannot be utilised.

**Comment by fcyu** [comment]
It can. I think MSBooster will strip the PTMs that the model doesn't support and shift the peaks after getting the predicted spectra.

Best,

Fengchao

**Comment by yangkl96** [comment]
Here is the request link: https://www.dropbox.com/request/c9sgqiJOUG1EqZb0AYx0

Thanks for the suggestion, I can add a warning or documentation.

**Comment by BenSamy2020** [comment]
Hi @yangkl96,

Done thank you.

**Comment by BenSamy2020** [comment]
Hi can I get an update on this thank you.

**Comment by yangkl96** [comment]
I am making some final changes and should have a new version for you by tomorrow

**Comment by yangkl96** [comment]
Hi Ben,

Thanks for your patience. Can you try out the newest [version 1.2.56 here](https://www.dropbox.com/home/Kevin%20Yang/msboosters/BenSamy2020_msbooster1.2.52)?

**Comment by BenSamy2020** [comment]
Greeting @yangkl96 ,

Please share the file again, thank you. 

Regards,
Ben

**Comment by yangkl96** [comment]
https://www.dropbox.com/scl/fo/sioaysait4lkbdkvk5bn6/AKGomsKTlP6fSup8nnL43YE?rlkey=3k61o6l0o2wsg3m5ml2buv4f1&st=uqvbom7j&dl=0

You can use the most recent upload, MSBooster-1.2.59.jar

**Comment by BenSamy2020** [comment]
[log_2024-10-22_00-29-18.txt](https://github.com/user-attachments/files/17468797/log_2024-10-22_00-29-18.txt)

Greetings @yangkl96,

I am still facing issue with MSBooster.

Operating on slice 10 of 10: 
	Fragment index slice generated in 77.54 s
	001. SLAS2_1845_DIABETES-MELLITUS.mzBIN_calibrated 0.2 s
		[progress: 31545/31669 (100%) - 3140 spectra/s]​
		[progress: 31669/31669 (100%) - 2988 spectra/s] 10.6s
		Building spectral index for the mzBIN_calibrated file 34.3 s
		Rescoring with peak tracing 7.4 s
		Picking top PSMs for each precursor 0.1 s
		Rescoring 1.2 s
		Writing results 0.6 s
***************************MAIN SEARCH DONE IN 16.080 MIN***************************

*******************************TOTAL TIME 17.322 MIN********************************
Process 'MSFragger' finished, exit code: 0
MSFragger move pepxml
D:\FragPipe-jre-22.0\jre\bin\java.exe -cp D:\FragPipe-jre-22.0\lib\fragpipe-22.0.jar;/D:/FragPipe-jre-22.0/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\SLAS2_1845_DIABETES-MELLITUS_rank1.pepXML D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2\SLAS2_NON_CANCER_282\SLAS2_1845_DIABETES-MELLITUS_rank1.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pepxml
D:\FragPipe-jre-22.0\jre\bin\java.exe -cp D:\FragPipe-jre-22.0\lib\fragpipe-22.0.jar;/D:/FragPipe-jre-22.0/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\SLAS2_1845_DIABETES-MELLITUS_rank2.pepXML D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2\SLAS2_NON_CANCER_282\SLAS2_1845_DIABETES-MELLITUS_rank2.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pepxml
D:\FragPipe-jre-22.0\jre\bin\java.exe -cp D:\FragPipe-jre-22.0\lib\fragpipe-22.0.jar;/D:/FragPipe-jre-22.0/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\SLAS2_1845_DIABETES-MELLITUS_rank3.pepXML D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2\SLAS2_NON_CANCER_282\SLAS2_1845_DIABETES-MELLITUS_rank3.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pepxml
D:\FragPipe-jre-22.0\jre\bin\java.exe -cp D:\FragPipe-jre-22.0\lib\fragpipe-22.0.jar;/D:/FragPipe-jre-22.0/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\SLAS2_1845_DIABETES-MELLITUS_rank4.pepXML D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2\SLAS2_NON_CANCER_282\SLAS2_1845_DIABETES-MELLITUS_rank4.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pepxml
D:\FragPipe-jre-22.0\jre\bin\java.exe -cp D:\FragPipe-jre-22.0\lib\fragpipe-22.0.jar;/D:/FragPipe-jre-22.0/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\SLAS2_1845_DIABETES-MELLITUS_rank5.pepXML D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2\SLAS2_NON_CANCER_282\SLAS2_1845_DIABETES-MELLITUS_rank5.pepXML
Process 'MSFragger move pepxml' finished, exit code: 0
MSFragger move pin
D:\FragPipe-jre-22.0\jre\bin\java.exe -cp D:\FragPipe-jre-22.0\lib\fragpipe-22.0.jar;/D:/FragPipe-jre-22.0/lib/commons-io-2.15.1.jar com.github.chhh.utils.FileMove --no-err D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\SLAS2_1845_DIABETES-MELLITUS.pin D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2\SLAS2_NON_CANCER_282\SLAS2_1845_DIABETES-MELLITUS.pin
Process 'MSFragger move pin' finished, exit code: 0
MSBooster [Work dir: D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2]
D:\FragPipe-jre-22.0\jre\bin\java.exe -Xmx120G -cp D:\FragPipe-jre-22.0\tools\MSBooster-1.2.59.jar;D:\FragPipe-jre-22.0\tools\batmass-io-1.33.4.jar Features.MainClass --paramsList D:\MSFragger_Temp\Healthy_Pre_Post_Exercise\Output_LFQ-MBR_OpenProt_2\msbooster_params.txt
Error: Could not find or load main class Features.MainClass
Caused by: java.lang.ClassNotFoundException: Features.MainClass
Process 'MSBooster' finished, exit code: 1
Process returned non-zero exit code, stopping

~~~~~~~~~~~~~~~~~~~~
Cancelling 2063 remaining tasks

**Comment by yangkl96** [comment]
You have to run it with FragPipe 22.1: https://www.dropbox.com/scl/fi/af1f06z39790c7bz0utwv/FragPipe-22.1-build06.zip?rlkey=ph04c6on0edy8grmimx55589c&st=y8vo725z&dl=0
![image](https://github.com/user-attachments/assets/12edb097-f100-4bd5-8aa8-4cd7fba5b5e4)
