### ISSUE TITLE
PTMProphet Warning

### ISSUE THREAD

**Issue by Amelia811** [Nesvilab/FragPipe#2603]
**- Upload your log file**
(If a log file h

[log_2025-12-26_08-52-29.txt](https://github.com/user-attachments/files/24343647/log_2025-12-26_08-52-29.txt)
[log_2025-12-26_08-27-48.txt](https://github.com/user-attachments/files/24343648/log_2025-12-26_08-27-48.txt)

asn't been generated, go to the 'Run' tab in FragPipe, click 'Export Log', zip the resulting "log_[date_time].txt" file to avoid truncation, then attach the zipped file by drag & drop here.)

**- Describe the issue or question:**

Hello,
I would like to report an issue observed when running PTMProphet within FragPipe on Windows. The problem is reproducible and affects multiple mzML files, with different scan numbers failing in different runs.
You can find two logs in the attachment.
During PTMProphet execution, the program repeatedly fails to read a specific MS/MS scan from a calibrated mzML file. The scan number is not fixed across runs or files. For example:
In one run, PTMProphet repeatedly failed to read scan 5906 from one calibrated mzML file.
In a subsequent run, PTMProphet repeatedly failed to read scan 5635 from a different calibrated mzML file.
Can you please help?
Thank you.

**Comment by 2021221221** [comment]
I’m seeing the same error on my side

<img width="1223" height="390" alt="Image" src="https://github.com/user-attachments/assets/56001cee-63f0-49fa-8207-405480511d5f" />

**Comment by fcyu** [comment]
This is a known bug that has been fixed in the latest version of FragPipe. Please upgrade it.

Thanks,

Fengchao

**Comment by Amelia811** [comment]
[log_2025-12-26_10-25-05.txt](https://github.com/user-attachments/files/24351786/log_2025-12-26_10-25-05.txt)

I tried the latest version. It still happened. Please see the attached log. Thanks.

**Comment by fcyu** [comment]
Hmm. Could you share the `20251222_ZCY_293T_IPFlagRIPK1_FOXP3_phos_Slot1-32_1_15894.d` and `2025-12-15-decoys-contam-Bing_human_uniprotkb_AND_reviewed_true_AND_model_o_2025_02_08_mouseRIPK1_mouseFOXP3.fasta.fas` with me?

Thanks,

Fengchao

**Comment by Amelia811** [comment]
The files are too big. I sent them via an email to you. Thank you.

**Comment by fcyu** [comment]
I didn't receive any emails.

Thanks,

Fengchao

**Comment by Amelia811** [comment]
I sent an email to notifications@github.com. It shows successfully delivered to mail server.

**Comment by fcyu** [comment]
I don't think that is the correct email address if you wanted to email it to me. Could you use `yufeATumich.edu` (replace `AT` with `@`)?

Thanks,

Fengchao

**Comment by Amelia811** [comment]
Thank you, I sent emails to yufeATumich.edu.

**Comment by fcyu** [comment]
Thanks for sharing the files. The error was caused by a new bug specifically related to ddaPASEF. It has been fixed. Let me know if you want to try the pre-released version.

Best,

Fengchao

**Comment by Amelia811** [comment]
Thank you. Please share the pre-release version with me.

**Comment by fcyu** [comment]
Sent to you by email.

Thanks,

Fengchao

**Comment by Amelia811** [comment]
Thanks. May I inquire about the expected release date of the new version?

**Comment by fcyu** [comment]
I don't know.

Best,

Fengchao

**Comment by anesvi** [comment]
We will see if any other issues reported by our users and release a minor update 24.1

**Comment by Amelia811** [comment]
Thank you. Looking forward to the new version...

**Comment by 2021221221** [comment]
Thank you for the update. I’m experiencing the same issue as well and would like to try the pre-release version.










-----原始邮件-----
发件人:Fengchao ***@***.***>
发送时间:2025-12-29 09:16:53 (星期一)

收件人: Nesvilab/FragPipe ***@***.***>
抄送: 2021221221 ***@***.***>, Comment ***@***.***>
主题: Re: [Nesvilab/FragPipe] PTMProphet Warning (Issue #2603)



fcyu left a comment (Nesvilab/FragPipe#2603)

I don't know.

Best,

Fengchao
