### ISSUE TITLE
Adjust `I` and `L` in the psm.tsv, peptide.tsv, and ion.tsv after razor assignment

### ISSUE THREAD

**Issue by fcyu** [Nesvilab/FragPipe#500]
The razor assignment might make an alternative protein as the razor protein. Since we don't distinguish `I` and `L` in the protein mapping, some peptides might not exist in their razor protein. Need to change some `I` to `L`, or `L` to `I` after razor assignment, so that the peptides in the tsv files are correct.

Best,

Fengchao

**Comment by fcyu** [comment]
@prvst Is it done?

Best,

Fengchao

**Comment by prvst** [comment]
done

**Comment by fcyu** [comment]
Thanks,

**Comment by fcyu** [comment]
I guess this issue was actually not fixed according to the user's latest feedback: https://github.com/Nesvilab/FragPipe/issues/771#issuecomment-1351298544

Felipe @prvst , can you take a look?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Fixed in Philosopher 4.8.0

Best,

Fengchao

**Comment by hollenstein** [comment]
Dear FragPipe team,

I've reanalyzed my test samples with the new version of FragPipe and Philosopher, and for some peptides I still get wrongly reported "L" when there should be an "I". For example the peptide "ELIEELIAK" is reported as "ELIEELLAK". So it seems that not all "L" are converted to "I". Also the reported peptide sequence "ELIEELLAK" does not occur in the fasta file. 

In contrast to the previous [issue 771](https://github.com/Nesvilab/FragPipe/issues/771), the reported peptide start and end positions seem to be correct now.

Version info:
FragPipe version 19.1
MSFragger version 3.7
IonQuant version 1.8.10
Philosopher version 4.8.0

Would be great if you could look into this once more.

Best,
David

**Comment by fcyu** [comment]
Seems to be the same issue as https://github.com/Nesvilab/philosopher/issues/409 Need Felipe to fix.

Best,

Fengchao

**Comment by prvst** [comment]
Please use Philosopher version 4.8.1

**Comment by hollenstein** [comment]
I've run it now with Philosopher version 4.8.1, and the issue is still present.
