### ISSUE TITLE
Download database

### ISSUE THREAD

**Issue by bearl86** [Nesvilab/FragPipe#641]
Hello

I am trying to download a FASTA sequence from Database window

![image](https://user-images.githubusercontent.com/103437377/162767569-72a985f2-271f-4279-8ea4-bfdf052542ee.png)

and I am getting this Java error

![image](https://user-images.githubusercontent.com/103437377/162767714-1da18304-1dc0-4eee-9d27-e9c5257ec7df.png)

In addition, If I use a local fasta available in my PC, using the "Browse" button and then the "Add decoys" button, I am also getting another Java error:

![image](https://user-images.githubusercontent.com/103437377/162768165-a591cf6d-5d06-4964-9368-4a346e8ff76e.png)

Any ideas? I have installed the latest version of Java

Many thanks in advance

**Comment by fcyu** [comment]
Can you show me the output in the Run tab?

Thanks,

Fengchao

**Comment by bearl86** [comment]
Yes sure,

![image](https://user-images.githubusercontent.com/103437377/162768868-9e6030cb-56fe-4477-9fac-f23f4e3b331c.png)

**Comment by fcyu** [comment]
Can you run those two commands starting from `E:\FragPipe-jre-17.1.....` in cmd.exe, and show me the output?

Thanks,

Fengchao

**Comment by fcyu** [comment]
No, from cmd.exe, which is the Windows command line.

Best,

Fengchao

**Comment by bearl86** [comment]
Done

![image](https://user-images.githubusercontent.com/103437377/162772534-b504082b-e67a-4965-bdc5-80c52c3aad30.png)

**Comment by fcyu** [comment]
I am sorry if I did not say it clearly. Please run those two commands starting from `E:\FragPipe-jre-17.1.....` in cmd.exe, and show me the output?

More specifically, they should be 
![image](https://user-images.githubusercontent.com/6926299/162772957-b70a6188-73d9-4ef0-ad78-8ce7f0161bb9.png)
and
![image](https://user-images.githubusercontent.com/6926299/162773007-490812d5-c771-49f4-9eb4-7aa7b0af2b98.png)

Please copy the full commands from the console in the Run tab.

Best,

Fengchao

**Comment by fcyu** [comment]
You need to run it in the following folder.
![image](https://user-images.githubusercontent.com/6926299/162778988-0e8ab8d3-350a-46eb-853a-fc87a1cc1963.png)

Please copy the whole command. You missed `ck` in the `--nocheck` flag.

Please also run the second command.

Best,

Fengchao

**Comment by bearl86** [comment]
Hi Fengchao, I think that I do not understand what I have to do, I am sorry.
Could you explain me what I need to test in more detail?

**Comment by bearl86** [comment]
Thanks for your pacience
Here the ouput obtained
![image](https://user-images.githubusercontent.com/103437377/162787822-69c6b5f9-7c66-472b-8e18-a9e0221cbfb7.png)

**Comment by fcyu** [comment]
You should copy the **whole** command from your Run tab. I cannot do that because your screenshot did not show the whole command. But you should be able to copy the run the **whole** command.

Best,

Fengchao
